const database = require('./Database');

exports.getSales = async function (req, res, callback) {
    var returnString = "";
    console.log("Get sales");

}

exports.getSalesChartInfo = async function (req, res, callback) {
    var returnString = "";
    console.log("Get sales");
   
}

exports.getSalesDates = async function (req, res, callback) {
    var returnString = "";
    console.log("Get sales");

   
}


exports.deleteSale = async function (req, res, callback) {
    const id = req.body.id;
    console.log(id);
   
}